package com.huiqiyikang.assessment.service;
import com.huiqiyikang.assessment.entity.*; import com.huiqiyikang.assessment.mapper.*; import org.springframework.stereotype.Service; import java.util.*;
@Service public class ClassRoomService { final ClassRoomRepository classes; final ClassMemberRepository members; final ClassInviteCodeRepository codes; final ClassQuestionRepository classQuestions; final QuestionRepository questions; final StudentRepository students; final TeacherRepository teachers;
 public ClassRoomService(ClassRoomRepository c,ClassMemberRepository m,ClassInviteCodeRepository i,ClassQuestionRepository q,QuestionRepository questions,StudentRepository s,TeacherRepository t){classes=c;members=m;codes=i;classQuestions=q;this.questions=questions;students=s;teachers=t;}
 public Optional<ClassRoom> findById(Long id){return classes.findById(id);} public ClassRoom save(ClassRoom x){return classes.save(x);} public ClassInviteCode save(ClassInviteCode x){return codes.save(x);} public ClassMember save(ClassMember x){return members.save(x);} public ClassQuestion save(ClassQuestion x){return classQuestions.save(x);} public List<ClassRoom> findByTeacherUserId(Long id){return classes.findByTeacherUserId(id);} public List<ClassMember> findByStudentUserIdAndStatus(Long id,String s){return members.findByStudentUserIdAndStatus(id,s);} public List<ClassMember> findByClassIdAndStatus(Long id,String s){return members.findByClassIdAndStatus(id,s);} public List<ClassQuestion> findQuestions(Long id,String s){return classQuestions.findByClassIdAndStatus(id,s);} public Optional<ClassInviteCode> findByCodeAndStatus(String c,String s){return codes.findByCodeAndStatus(c,s);} public Optional<ClassInviteCode> findFirstByClassIdAndStatus(Long id,String s){return codes.findFirstByClassIdAndStatus(id,s);} public Optional<ClassQuestion> findByClassIdAndQuestionId(Long c,Long q){return classQuestions.findByClassIdAndQuestionId(c,q);} public boolean existsStudent(Long id){return students.existsByUserId(id);} public boolean existsTeacher(Long id){return teachers.existsByUserId(id);}
 public Optional<ClassMember> findByClassIdAndStudentUserId(Long c,Long u){return members.findByClassIdAndStudentUserId(c,u);} 
 public List<ClassRoom> managed(Long id){return classes.findByTeacherUserId(id);} public List<ClassMember> joined(Long id){return members.findByStudentUserIdAndStatus(id,"active");} public List<ClassMember> members(Long id){return members.findByClassIdAndStatus(id,"active");} public List<ClassQuestion> questions(Long id){return classQuestions.findByClassIdAndStatus(id,"active");} public Optional<ClassMember> member(Long c,Long u){return members.findByClassIdAndStudentUserId(c,u);} public Optional<ClassInviteCode> code(String c,String s){return codes.findByCodeAndStatus(c,s);} public Optional<ClassInviteCode> activeCode(Long c){return codes.findFirstByClassIdAndStatus(c,"active");} public Optional<ClassQuestion> classQuestion(Long c,Long q){return classQuestions.findByClassIdAndQuestionId(c,q);} public Optional<Question> question(Long id){return questions.findById(id);} public boolean student(Long id){return students.existsByUserId(id);} public boolean teacher(Long id){return teachers.existsByUserId(id);}
 /** 批量取班级（学生「我的班级」列表用），替代逐个 findById。 */
 public List<ClassRoom> findAllById(java.util.Collection<Long> ids){return classes.findAllById(ids);}
 /** 不看状态地按邀请码查，供「生成不重复的码」使用（code 列是 UNIQUE，历史失效码也要避开）。 */
 public Optional<ClassInviteCode> findByCode(String code){return codes.findByCode(code);}
 /** 班级人数/题数只数行数，不再把整份列表读出来再 size()。 */
 public long memberCount(Long id){return members.countByClassIdAndStatus(id,"active");}
 public long questionCount(Long id){return classQuestions.countByClassIdAndStatus(id,"active");}
}
