package com.huiqiyikang.assessment.controller;
import com.huiqiyikang.assessment.entity.*; import com.huiqiyikang.assessment.service.*;

import cn.dev33.satoken.stp.StpUtil; import com.huiqiyikang.assessment.common.*;
import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.HttpStatus; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.security.SecureRandom; import java.time.Instant; import java.util.*;

@RestController @RequestMapping("/api/classes")
public class ClassRoomController {
 private final ClassRoomService classes; private final ClassRoomService members; private final ClassRoomService codes; private final ClassRoomService classQuestions; private final QuestionService questions; private final AccountService students; private final AccountService teachers; private final SecureRandom random=new SecureRandom();
 private final AbilityService abilities;
 public ClassRoomController(ClassRoomService c,ClassRoomService m,ClassRoomService i,ClassRoomService q,QuestionService questions,AccountService s,AccountService t,AbilityService abilities){classes=c;members=m;codes=i;classQuestions=q;this.questions=questions;students=s;teachers=t;this.abilities=abilities;}
 public record Create(@NotBlank String name,String description){}
 @PostMapping public ApiResponse<?> create(@Valid @RequestBody Create r){Long uid=uid();if(!teachers.existsByUserId(uid))throw new BusinessException("只有教师可以创建班级");ClassRoom c=classes.save(new ClassRoom(uid,r.name(),r.description()));ClassInviteCode code=codes.save(new ClassInviteCode(c.getId(),newCode()));return ApiResponse.ok(Map.of("id",c.getId(),"name",c.getName(),"description",Optional.ofNullable(c.getDescription()).orElse(""),"inviteCode",code.getCode()));}
 @GetMapping("/managed") public ApiResponse<?> managed(){if(!teachers.existsByUserId(uid()))throw new BusinessException("当前账号不是教师");return ApiResponse.ok(classes.findByTeacherUserId(uid()));}
 @GetMapping("/joined") public ApiResponse<?> joined(){return ApiResponse.ok(members.findByStudentUserIdAndStatus(uid(),"active").stream().map(m->classes.findById(m.getClassId()).orElse(null)).filter(Objects::nonNull).toList());}
 /**
  * 学生能力数据：一次返回雷达图、技能树、趋势曲线、上一次对比需要的全部数据。
  * 所有查询都按 classId 隔离；调用者必须是该班级的 active 成员。
  */
 @GetMapping("/{id}/my-ability") public ApiResponse<?> myAbility(@PathVariable Long id){if(!members.findByClassIdAndStudentUserId(id,uid()).map(m->"active".equals(m.getStatus())).orElse(false))throw new BusinessException("不是该班级有效成员",HttpStatus.FORBIDDEN);return ApiResponse.ok(abilities.myAbility(id,uid()));}
 @GetMapping("/{id}") public ApiResponse<?> detail(@PathVariable Long id){ClassRoom c=classes.findById(id).orElseThrow(()->new BusinessException("班级不存在"));if(!c.getTeacherUserId().equals(uid())&&!members.findByClassIdAndStudentUserId(id,uid()).map(m->"active".equals(m.getStatus())).orElse(false))throw new BusinessException("无权访问该班级");Map<String,Object> data=new LinkedHashMap<>();data.put("classroom",c);data.put("memberCount",members.findByClassIdAndStatus(id,"active").size());data.put("questionCount",classQuestions.findByClassIdAndStatus(id,"active").size());data.put("inviteCode",codes.findFirstByClassIdAndStatus(id,"active").map(ClassInviteCode::getCode).orElse(null));return ApiResponse.ok(data);}
 @PostMapping("/join") @Transactional public ApiResponse<?> join(@RequestBody Map<String,String> body){String input=body.getOrDefault("inviteCode","").trim();ClassInviteCode code=codes.findByCodeAndStatus(input,"active").orElseThrow(()->new BusinessException("邀请码无效或已失效"));if(!students.existsByUserId(uid()))throw new BusinessException("当前账号不是学生");ClassMember m=members.findByClassIdAndStudentUserId(code.getClassId(),uid()).orElse(null);if(m!=null&&"active".equals(m.getStatus()))throw new BusinessException("已加入该班级");if(m==null)members.save(new ClassMember(code.getClassId(),uid()));else{m.setStatus("active");m.setLeftAt(null);m.setRemovedAt(null);members.save(m);}return ApiResponse.ok(classes.findById(code.getClassId()).orElseThrow());}
 @DeleteMapping("/{id}/leave") public ApiResponse<Void> leave(@PathVariable Long id){ClassMember m=members.findByClassIdAndStudentUserId(id,uid()).orElseThrow(()->new BusinessException("不是该班级成员"));m.setStatus("left");m.setLeftAt(Instant.now());members.save(m);return ApiResponse.ok();}
 @GetMapping("/{id}/members") public ApiResponse<?> memberList(@PathVariable Long id){owned(id);return ApiResponse.ok(members.findByClassIdAndStatus(id,"active"));}
 @DeleteMapping("/{id}/members/{studentId}") public ApiResponse<Void> removeMember(@PathVariable Long id,@PathVariable Long studentId){owned(id);ClassMember m=members.findByClassIdAndStudentUserId(id,studentId).orElseThrow(()->new BusinessException("成员不存在"));m.setStatus("removed");m.setRemovedAt(Instant.now());members.save(m);return ApiResponse.ok();}
 @PostMapping("/{id}/invite-code") public ApiResponse<?> refresh(@PathVariable Long id){owned(id);codes.findFirstByClassIdAndStatus(id,"active").ifPresent(old->{old.setStatus("invalidated");old.setInvalidatedAt(Instant.now());codes.save(old);});return ApiResponse.ok(codes.save(new ClassInviteCode(id,newCode())));}
 @GetMapping("/{id}/questions") public ApiResponse<?> classQuestions(@PathVariable Long id){owned(id);return ApiResponse.ok(classQuestions.findQuestions(id,"active").stream().map(x->questions.findById(x.getQuestionId()).orElse(null)).filter(Objects::nonNull).toList());}
 @PostMapping("/{id}/questions/{questionId}") public ApiResponse<?> addQuestion(@PathVariable Long id,@PathVariable Long questionId){owned(id);Question q=questions.findById(questionId).orElseThrow(()->new BusinessException("题目不存在"));if(!q.getOwnerUserId().equals(uid()))throw new BusinessException("只能添加自己拥有的题目");if(!"active".equals(q.getStatus()))throw new BusinessException("下线题目不能加入班级题库");ClassQuestion x=classQuestions.findByClassIdAndQuestionId(id,questionId).orElse(null);if(x==null) x=new ClassQuestion(id,questionId);x.setStatus("active");x.setRemovedAt(null);return ApiResponse.ok(classQuestions.save(x));}
 @DeleteMapping("/{id}/questions/{questionId}") public ApiResponse<Void> removeQuestion(@PathVariable Long id,@PathVariable Long questionId){owned(id);ClassQuestion x=classQuestions.findByClassIdAndQuestionId(id,questionId).orElseThrow(()->new BusinessException("班级题库中不存在该题目"));x.setStatus("removed");x.setRemovedAt(Instant.now());classQuestions.save(x);return ApiResponse.ok();}
 private Long uid(){return StpUtil.getLoginIdAsLong();} private void owned(Long id){ClassRoom c=classes.findById(id).orElseThrow(()->new BusinessException("班级不存在",HttpStatus.NOT_FOUND));if(!c.getTeacherUserId().equals(uid()))throw new BusinessException("无权操作该班级",HttpStatus.FORBIDDEN);} private String newCode(){return String.format("%06d",random.nextInt(1_000_000));}
}
