package com.huiqiyikang.assessment.controller;
import com.huiqiyikang.assessment.entity.*; import com.huiqiyikang.assessment.service.*;

import cn.dev33.satoken.stp.StpUtil;
import com.huiqiyikang.assessment.common.*;
import org.springframework.web.bind.annotation.*;
import java.util.*;
import java.util.stream.Collectors;

@RestController @RequestMapping("/api/teacher")
public class TeacherAssessmentController {
    private final AssessmentService assessments; private final TaskService tasks; private final AssessmentService questions; private final AssessmentService answers; private final ClassRoomService classes; private final AccountService users; private final AccountService teachers;
    public TeacherAssessmentController(AssessmentService a,TaskService t,AssessmentService q,AssessmentService aa,ClassRoomService c,AccountService u,AccountService tr){assessments=a;tasks=t;questions=q;answers=aa;classes=c;users=u;teachers=tr;}
    // Self-assessments carry a NULL task_id, so compare from the task side to avoid a null dereference.
    @GetMapping("/assessment-tasks/{taskId}/results") public ApiResponse<?> taskResults(@PathVariable Long taskId){AssessmentTask task=ownedTask(taskId);return ApiResponse.ok(assessments.findAll().stream().filter(a->task.getId().equals(a.getTaskId())).map(this::summary).toList());}
    @GetMapping("/classes/{classId}/results") public ApiResponse<?> classResults(@PathVariable Long classId){ClassRoom c=classes.findById(classId).orElseThrow(()->new BusinessException("班级不存在"));if(!c.getTeacherUserId().equals(uid()))throw new BusinessException("无权访问该班级");Set<Long> taskIds=tasks.findByClassIdAndStatus(classId,"active").stream().map(AssessmentTask::getId).collect(Collectors.toSet());return ApiResponse.ok(assessments.findAll().stream().filter(a->taskIds.contains(a.getTaskId())).map(this::summary).toList());}
    @GetMapping("/assessments/{id}") public ApiResponse<?> detail(@PathVariable Long id){Assessment a=assessments.findById(id).orElseThrow(()->new BusinessException("测评不存在"));AssessmentTask task=ownedTask(a.getTaskId());List<AssessmentQuestion> qs=questions.findByAssessmentIdOrderBySequenceNo(id);Map<Long,AssessmentAnswer> answerMap=answers.findByAssessmentQuestionIdIn(qs.stream().map(AssessmentQuestion::getId).toList()).stream().collect(Collectors.toMap(AssessmentAnswer::getAssessmentQuestionId,x->x));List<Map<String,Object>> questionDetails=qs.stream().map(q->{Map<String,Object> d=new LinkedHashMap<>();d.put("question",q);d.put("messages",assessments.findMessages(q.getId()));d.put("answer",answerMap.get(q.getId()));return d;}).toList();Map<String,Object> result=new LinkedHashMap<>();result.put("assessment",a);result.put("task",task);result.put("classroom",classes.findById(task.getClassId()).orElse(null));result.put("student",users.findById(a.getStudentUserId()).orElse(null));result.put("questions",questionDetails);result.put("hasScoringFailure",answerMap.values().stream().anyMatch(x->"scoring_failed".equals(x.getResultStatus())));return ApiResponse.ok(result);}
    private Map<String,Object> summary(Assessment a){Map<String,Object> r=new LinkedHashMap<>();User student=users.findById(a.getStudentUserId()).orElse(null);AssessmentTask task=tasks.findById(a.getTaskId()).orElse(null);List<AssessmentQuestion> qs=questions.findByAssessmentIdOrderBySequenceNo(a.getId());r.put("assessmentId",a.getId());r.put("taskId",a.getTaskId());r.put("classId",a.getClassId());r.put("className",task==null?null:classes.findById(task.getClassId()).map(ClassRoom::getName).orElse(null));r.put("taskTitle",task==null?null:task.getTitle());r.put("studentId",a.getStudentUserId());r.put("studentName",student==null?null:student.getName());r.put("studentAccount",student==null?null:student.getUsername());r.put("status",a.getStatus());r.put("startedAt",a.getStartedAt());r.put("completedAt",a.getCompletedAt());r.put("totalScore",a.getTotalScore());r.put("averageScore",a.getAverageScore());r.put("abilityLevel",a.getAbilityLevel());r.put("completedQuestionCount",qs.stream().filter(q->"answered".equals(q.getStatus())).count());r.put("questionCount",a.getQuestionCount()!=null&&a.getQuestionCount()>0?a.getQuestionCount():(task==null?qs.size():task.getQuestionCount()));r.put("hasScoringFailure",answers.findByAssessmentQuestionIdIn(qs.stream().map(AssessmentQuestion::getId).toList()).stream().anyMatch(x->"scoring_failed".equals(x.getResultStatus())));return r;}
    private AssessmentTask ownedTask(Long id){if(!teachers.existsByUserId(uid()))throw new BusinessException("当前账号不是教师");AssessmentTask task=tasks.findById(id).orElseThrow(()->new BusinessException("测评任务不存在"));if(!task.getTeacherUserId().equals(uid()))throw new BusinessException("无权访问该测评任务");return task;}
    private Long uid(){return StpUtil.getLoginIdAsLong();}
}
